title: Petrarch's Itinera
description: Linee guida per i compilatori
theme: just-the-docs

url: https://petrarchsitinera.github.io/linee-guida

aux_links: 
  Template Repository: https://petrarchsitinera.github.io/linee-guida
