remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Petrarch's Itinera
description: Linee guida per i compilatori
cover-img: "/assets/images/itinera_logo.jpg"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
